Fix systemd watchdog keepalive timing logic
Inconsistent variable name was causing:

    if time.time() - last_notify > sd_min_keepalive_rate:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'